all: ls cp cp2 getpid simpleshell errmsg uidgid

ls:
	gcc -o ls ls.c

cp:
	gcc -o cp cp.c

cp2:
	gcc -o cp2 cp2.c

getpid:
	gcc -o getpid getpid.c

simpleshell:
	gcc -o simpleshell simpleshell.c

errmsg:
	gcc -o errmsg errmsg.c

uidgid:
	gcc -o uidgid uidgid.c
